export const destinationsCorePackageId =
  "@agentscope/destinations-core" as const;

export {
  commitLocalResourceConfiguration,
  isLocalResourceConfigurationCommitError,
  LocalResourceConfigurationCommitError,
  LocalResourceConfigurationAuthorityError,
  type LocalResourceConfigurationAuthority,
  type LocalResourceConfigurationCommitEvidence,
} from "./local-resource-configuration-authority.js";

export {
  defineLocalResourceLifecycleDeclaration,
  DestinationLocalResourceLifecycleError,
  isLocalResourceLifecycleCapability,
  isLocalResourceLifecycleDeclaration,
  LOCAL_RESOURCE_LIFECYCLE_OPERATIONS,
  type LocalResourceLifecycleCapability,
  type LocalResourceLifecycleDeclaration,
  type LocalResourceLifecycleDeclarationInput,
  type LocalResourceLifecycleOperation,
} from "./local-resource-lifecycle.js";
export {
  applyLocalResourceLifecyclePlan,
  applyLocalResourceMaintenancePlan,
  completeLocalResourceLifecycle,
  inspectLocalResourceDoctor,
  inspectLocalResourceMaintenancePlan,
  recoverLocalResourceLifecycle,
  recoverLocalResourceMaintenance,
  compileLocalResourceLifecycleHandlerRegistry,
  defineLocalResourceLifecycleHandler,
  getLocalResourceLifecycleHandlerCapability,
  inspectLocalResourceLifecyclePlan,
  inspectRetainedLocalResourceDelete,
  isLocalResourceLifecycleHandlerRegistry,
  localResourceLifecycleHandlerRegistryUsesDestinationRegistry,
  LocalResourceLifecycleHandlerError,
  type LocalResourceLifecycleApplyResult,
  type LocalResourceLifecycleContext,
  type LocalResourceLifecycleDeadline,
  type LocalResourceLifecycleHandler,
  type LocalResourceLifecycleHandlerImplementation,
  type LocalResourceLifecycleHandlerRegistry,
  type LocalResourceLifecycleMutationOperation,
  type LocalResourceLifecyclePlanEvidence,
  type LocalResourceLifecycleRecoveryContext,
  type LocalResourceBackupAuthority,
  type LocalResourceDoctorContext,
  type LocalResourceDoctorInspection,
  type LocalResourceMaintenanceContext,
  type LocalResourceMaintenanceOperation,
  type LocalResourceMaintenancePlanEvidence,
  type LocalResourceMaintenanceRecoveryContext,
  type LocalResourceMaintenanceResult,
  type LocalResourceRetainedDeleteAuthority,
} from "./local-resource-handler.js";

export {
  compileDestinationRegistry,
  defineDestinationDescriptor,
  DestinationDescriptorError,
  getDestinationDescriptor,
  isDestinationDescriptor,
  parseDestinationSettings,
  type DeliveryIdentitySupport,
  type DestinationDescriptor,
  type DestinationDescriptorInput,
  type DestinationRegistry,
  type DestinationSettings,
  type DestinationTransportDeclaration,
  type RemoteEndpointCandidate,
  type ReporterFactoryContext,
  type RetrieverFactoryContext,
} from "./descriptor.js";
export {
  DestinationReachabilityError,
  defineDestinationReachabilityProbe,
  isDestinationReachabilityProbe,
  type DestinationReachabilityProbe,
  type DestinationReachabilityProbeInput,
  type DestinationReachabilityState,
} from "./reachability.js";
export {
  isReporterDeadline,
  MAXIMUM_REPORTER_TIMEOUT_MILLISECONDS,
  ReporterDeadlineError,
  reporterDeadlineRemainingMilliseconds,
  type ReporterDeadline,
} from "./deadline.js";
export {
  DestinationEndpointError,
  isValidatedDestinationEndpoint,
  type DestinationEndpointPolicy,
  type ValidatedDestinationEndpoint,
} from "./endpoint.js";
export {
  createCredentialSlotId,
  createDestinationCommandName,
  createDestinationConnectionId,
  createDestinationTypeId,
  DestinationIdentityError,
  type CredentialSlotId,
  type DestinationCommandName,
  type DestinationConnectionId,
  type DestinationTypeId,
} from "./identity.js";
export {
  createDestinationReporter,
  createReporterReceipt,
  isDestinationReporter,
  MAXIMUM_REPORTER_BATCH_ITEMS,
  REPORTER_OUTCOMES,
  REPORTER_RECEIPT_REASON_VERSION,
  REPORTER_RECEIPT_REASONS,
  ReporterContractError,
  type RedactedTraceBatch,
  type Reporter,
  type ReporterAttempt,
  type ReporterImplementation,
  type ReporterOutcome,
  type ReporterReceipt,
  type ReporterReceiptReason,
} from "./reporter.js";
export {
  DestinationTransportError,
  executeBoundDestinationRequest,
  isBoundDestinationTransport,
  MAXIMUM_TRANSPORT_REQUEST_BYTES,
  MAXIMUM_TRANSPORT_RESPONSE_BYTES,
  type BoundDestinationTransport,
  type DestinationTransportRequest,
  type DestinationTransportResponse,
} from "./transport.js";
export {
  DestinationCredentialError,
  readReporterCredential,
  type CredentialSlot,
  type ReporterCredentialAccessor,
} from "./credentials.js";
export {
  DESTINATION_SETTINGS_LIMITS,
  DestinationDataError,
  type JsonObject,
  type JsonValue,
} from "./plain-data.js";
export {
  createTraceLocator,
  isTraceLocator,
  RetrievalIdentityError,
  type TraceLocator,
  type TraceLocatorInput,
} from "./retrieval-identity.js";
export {
  TRACE_SEARCH_DEFAULT_LIMIT,
  TRACE_SEARCH_MAXIMUM_LIMIT,
  TRACE_SEARCH_MAXIMUM_TAGS,
  TRACE_SEARCH_ORDERINGS,
  TraceQueryError,
  type TraceQueryFingerprint,
  type TraceSearchInput,
  type TraceSearchOrdering,
  type TraceSearchQuery,
} from "./retrieval-query.js";
export {
  createRetrievedTrace,
  createRetrieverSearchPage,
  createTraceSummary,
  isRetrievedTrace,
  isRetrieverSearchPage,
  isTraceSummary,
  RetrievalResultError,
  TRACE_SUMMARY_STATUSES,
  type PartialResultReason,
  type RetrievedTrace,
  type RetrievedTraceRepresentation,
  type RetrievalConsistency,
  type RetrieverSearchPage,
  type RetrieverSearchPageInput,
  type TraceSummary,
  type TraceSummaryInput,
  type TraceSummaryStatus,
} from "./retrieval-results.js";
export {
  createDestinationRetriever,
  createRetrieverFailure,
  createRetrieverSuccess,
  isDestinationRetriever,
  isRetrieverFailure,
  RETRIEVER_FAILURE_CODES,
  RetrieverContractError,
  type RetrievalContext,
  type Retriever,
  type RetrieverFailure,
  type RetrieverFailureCode,
  type RetrieverImplementation,
  type RetrieverOperationResult,
  type TraceGetBinding,
  type TraceGetRequest,
  type TraceSearchRequest,
} from "./retriever.js";
export {
  TraceCursorError,
  type TraceCursorBinding,
  type TraceSearchCursor,
} from "./retrieval-cursor.js";
export {
  isTraceSearchPage,
  TraceSearchPageError,
  type TraceSearchPage,
} from "./retrieval-page.js";
