export {
  CREDENTIAL_RESOLUTION_FAILURES,
  compileCredentialBackendRegistry,
  createCiEnvironmentCredentialAdapter,
  createCredentialOwnership,
  createCredentialResolutionContext,
  defineStoredCredentialBackendAdapter,
  isResolvedCredential,
  isCredentialOwnership,
  isCredentialResolutionContext,
  resolveCredentialReference,
  CredentialAdapterError,
  type CredentialBackend,
  type CredentialBackendAdapter,
  type CredentialBackendRegistry,
  type CredentialOwnership,
  type CredentialResolutionContext,
  type CredentialResolutionFailure,
  type CredentialResolutionResult,
  type ResolvedCredential,
  type StoredCredentialBackend,
  type StoredCredentialBackendImplementation,
} from "./configuration/credential-adapter.js";
export {
  configureCredential,
  credentialOwnershipMatches,
  recoverCredentialMutation,
  removeCredentialReference,
  retireCredentialReference,
  CredentialLifecycleError,
  type ConfigureCredentialInput,
  type CredentialConfigurationRequest,
  type CredentialConfigurationResult,
  type CredentialRemovalResult,
  type CredentialMutationRecoveryResult,
  type RemoveCredentialInput,
} from "./configuration/credential-lifecycle.js";
export {
  DOCTOR_FINDING_CODES,
  DoctorError,
  inspectAgentscopeDoctor,
  repairDoctorConfigurationTransaction,
  repairDoctorOperationalStateLock,
  type DoctorCredentialInspection,
  type DoctorConnectionInspection,
  type DoctorFinding,
  type DoctorFindingCode,
  type DoctorInspectionInput,
  type DoctorReport,
} from "./configuration/doctor.js";
export {
  createMacosKeychainCredentialAdapter,
  MacosKeychainAdapterError,
} from "./configuration/macos-keychain.js";
export {
  createWindowsCredentialManagerAdapter,
  WindowsCredentialManagerError,
} from "./configuration/windows-credential-manager.js";
export {
  createLinuxSecretServiceAdapter,
  LinuxSecretServiceError,
} from "./configuration/linux-secret-service.js";
export {
  AGENTSCOPE_HOME_DIRECTORY_NAME,
  AGENTSCOPE_HOME_ENVIRONMENT_VARIABLE,
  AgentscopeHomeError,
  createAgentscopeHomeResolver,
  ensureAgentscopeHomeLayout,
  isAgentscopeHome,
  type AgentscopeHome,
  type AgentscopeHomeResolver,
  type AgentscopeHomeResolverInput,
} from "./configuration/home.js";
export {
  CONFIGURATION_V1_TO_V2_MIGRATION,
  DEFAULT_CONFIGURATION_MIGRATION_REGISTRY,
  compileConfigurationMigrationRegistry,
  ConfigurationMigrationError,
  migrateConfigurationDocument,
  type ConfigurationMigration,
  type ConfigurationMigrationErrorCode,
  type ConfigurationMigrationRegistry,
} from "./configuration/migration.js";
export {
  PIPELINE_HEALTH_OUTCOMES,
  PIPELINE_HEALTH_STAGES,
  SANITIZED_DIAGNOSTIC_CODES,
  OperationalStateError,
  createOperationalStateStore,
  inspectOperationalState,
  inspectOperationalStateLock,
  recoverAbandonedOperationalStateLock,
  type CaptureCheckpointInput,
  type OperationalStateSnapshot,
  type OperationalStateLockInspection,
  type OperationalStateStore,
  type OperationalStateWriteResult,
  type PipelineHealthInput,
  type PipelineHealthOutcome,
  type PipelineHealthStage,
  type SanitizedDiagnosticCode,
  type SanitizedDiagnosticInput,
} from "./configuration/operational-state.js";
export {
  AGENTSCOPE_CONFIGURATION_VERSION,
  DEFAULT_HOOK_DEADLINE_MILLISECONDS,
  MAXIMUM_HOOK_DEADLINE_MILLISECONDS,
  MINIMUM_HOOK_DEADLINE_MILLISECONDS,
  AgentscopeConfigurationError,
  MAXIMUM_CONFIGURED_CONNECTIONS,
  MAXIMUM_DESTINATION_NAMESPACES,
  MAXIMUM_ROUTED_CONNECTIONS,
  createAgentscopeConfigurationIdentity,
  parseAgentscopeConfiguration,
  serializeAgentscopeConfiguration,
  type AgentscopeConfigurationSnapshot,
  type ConfigurationCredentialReference,
  type ConfiguredDestinationConnection,
} from "./configuration/schema.js";
export {
  CONFIGURATION_TRANSACTION_STEPS,
  ConfigurationStoreError,
  createConfigurationProcessIdentity,
  createConfigurationStore,
  isConfigurationProcessIdentity,
  isConfigurationStore,
  inspectConfigurationTransaction,
  inspectCredentialMutation,
  readConfigurationBackupSnapshot,
  readConfigurationForHook,
  readConfigurationSnapshot,
  recoverAbandonedConfigurationTransaction,
  writeConfigurationSnapshot,
  type ConfigurationOwnerState,
  type ConfigurationProcessIdentity,
  type ConfigurationRecoveryResult,
  type ConfigurationStore,
  type ConfigurationStoreErrorCode,
  type ConfigurationTransactionStep,
  type ConfigurationTransactionInspection,
  type ConfigurationWriteInput,
  type CredentialMutationInspection,
  type HookConfigurationReadResult,
} from "./configuration/transaction.js";

export {
  BUILTIN_REDACTION_POLICY_REFERENCES,
  DEFAULT_REDACTION_POLICY_REGISTRY,
  MAXIMUM_REDACTION_POLICY_BYTES,
  MAXIMUM_REDACTION_RULES,
  REDACTION_POLICY_IDENTITIES,
  REDACTION_POLICY_PROFILE,
  REDACTION_POLICY_PROFILE_FINGERPRINT,
  RedactionPolicyError,
  compileRedactionPolicyRegistry,
  resolveRedactionPolicy,
  type RedactionPolicyDefinition,
  type RedactionPolicyRegistry,
  type RedactionPolicyRule,
  type ResolvedRedactionPolicy,
} from "./redaction/policy.js";
export {
  runResolvedTraceLifecycle,
  type ResolvedRoutingLifecycleResult,
  type ResolvedLifecycleOperationalEvidence,
  type ResolvedTraceLifecycleInput,
  type ResolvedTraceLifecycleResult,
} from "./invocation/lifecycle.js";
export {
  inspectGitContextForDoctor,
  type DoctorGitInspection,
} from "./invocation/git-context.js";
export {
  type CaptureAdapter,
  type CaptureResume,
  type CaptureResumeRequest,
} from "./lifecycle.js";
