export { createCiEnvironmentCredentialReference } from "./credential-adapter.js";
export {
  applyDestinationLifecyclePlan,
  ConfigurationManagementError,
  applyAgentscopeConfigurationInitialization,
  configureDestinationConnection,
  createCiEnvironmentCredentialPreflight,
  createConfigurationManagementRuntime,
  initializeAgentscopeConfiguration,
  inspectAgentscopeConfigurationInitialization,
  inspectDestinationConfigureLifecyclePlan,
  inspectDestinationLifecyclePlan,
  recoverDestinationLifecycleMutation,
  listDestinationConnections,
  setDestinationRouting,
  unconfigureDestinationConnection,
  type ConfigurationManagementRuntime,
  type DestinationLifecyclePlan,
  type ConfigurationInitializationPlan,
  type ConfigurationCredentialPreflight,
  type ConfigureDestinationConnectionInput,
  type DestinationConfigurationResult,
  type DestinationConnectionSummary,
} from "./management.js";
export {
  AGENTSCOPE_HOME_DIRECTORY_NAME,
  AGENTSCOPE_HOME_ENVIRONMENT_VARIABLE,
  AgentscopeHomeError,
  createAgentscopeHomeResolver,
  type AgentscopeHome,
  type AgentscopeHomeResolver,
  type AgentscopeHomeResolverInput,
} from "./home.js";
export {
  ConfigurationStoreError,
  createConfigurationProcessIdentity,
  createConfigurationStore,
  readConfigurationSnapshot,
  type ConfigurationProcessIdentity,
  type ConfigurationStore,
} from "./transaction.js";
